// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0CVawjbPCH3Hj5cWC4DveDJPMa3Ck8g',
    appId: '1:927976205488:android:0fccef1485bfa48a39df75',
    messagingSenderId: '927976205488',
    projectId: 'wepark-9879c',
    storageBucket: 'wepark-9879c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQgzPzCbX_BNww-5xGN3GQwXoOtXNF6cs',
    appId: '1:927976205488:ios:dc1c10c246e5ecc239df75',
    messagingSenderId: '927976205488',
    projectId: 'wepark-9879c',
    storageBucket: 'wepark-9879c.appspot.com',
    androidClientId: '927976205488-08emvua9u9vflldhku694tlqppjl3k9c.apps.googleusercontent.com',
    iosClientId: '927976205488-t1df4apjiussjgq3jfno7o8bdqo7va16.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zqJb4I72TnLe3b1iDllO5exzIkWuWPo',
    appId: '1:927976205488:web:42edfb626f7a4c2b39df75',
    messagingSenderId: '927976205488',
    projectId: 'wepark-9879c',
    authDomain: 'wepark-9879c.firebaseapp.com',
    storageBucket: 'wepark-9879c.appspot.com',
    measurementId: 'G-6YFJNSZD6N',
  );

}