name: proyecto_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  go_router: ^13.2.4
  google_sign_in: ^6.1.5
  intl: ^0.19.0
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
