name: proyecto_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.6.0
  geocoding: ^3.0.0
  go_router: ^13.2.4
  google_maps_flutter: ^2.6.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  pay: ^2.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  firebase_core_web: ^2.17.0
  fl_chart: ^0.36.0  # Moved here from dev_dependencies

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true